{% set name = "opentelemetry-instrumentation-asyncpg" %}
{% set version = "0.24b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-asyncpg-{{ version }}.tar.gz
  sha256: 4bbd352fd50f78a313ac5f3835e968dfb32ad05403c94f462a2edf45ae83a879

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.24b0
    - opentelemetry-semantic-conventions ==0.24b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - asyncpg >=0.12.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asyncpg
  summary: OpenTelemetry instrumentation for AsyncPG
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
