{% set name = "opentelemetry-instrumentation-asyncpg" %}
{% set version = "0.32b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-asyncpg-{{ version }}.tar.gz
  sha256: d301e28c8214615a01213ec3b675d92f365bb09964a47cba8fcf1b884e657a0d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.32b0
    - opentelemetry-semantic-conventions ==0.32b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test ==0.25b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test ==0.25b1
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.26b1
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.27b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.28b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.28b1
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.29b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.30b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.30b1
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.31b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.32b0
    # - asyncpg >=0.12.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asyncpg
  summary: OpenTelemetry instrumentation for AsyncPG
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
