{% set name = "opentelemetry-instrumentation-asyncpg" %}
{% set version = "0.28b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-asyncpg-{{ version }}.tar.gz
  sha256: b24e81bbdf456be3ca96545ed94831d32af9051595c38ceb0c6b280b45f2d8fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.28b0
    - opentelemetry-semantic-conventions ==0.28b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test ==0.25b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test ==0.25b1
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.26b1
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.27b0
    # - asyncpg >=0.12.0
    # - opentelemetry-test-utils ==0.28b0
    # - asyncpg >=0.12.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asyncpg
  summary: OpenTelemetry instrumentation for AsyncPG
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
